//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.4927
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seasar.Fisshplate {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EFPMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EFPMessages() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Seasar.Fisshplate.EFPMessages", typeof(EFPMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   number of #end element(s) is invalid.(row no. {0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EFP00001 {
            get {
                return ResourceManager.GetString("EFP00001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   lack of #if element. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EFP00002 {
            get {
                return ResourceManager.GetString("EFP00002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} is not iteratable.(row no. {1}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EFP00003 {
            get {
                return ResourceManager.GetString("EFP00003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Maybe bind variable &quot;{0}&quot; is undefined in data or its value is null.(row no. {1}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EFP00004 {
            get {
                return ResourceManager.GetString("EFP00004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Header is invalid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EFP00005 {
            get {
                return ResourceManager.GetString("EFP00005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Footer is invalid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EFP00006 {
            get {
                return ResourceManager.GetString("EFP00006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Picture Type is JPG or PNG Only. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EFP00007 {
            get {
                return ResourceManager.GetString("EFP00007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   value of foreach max attribute must be integer.(row no. {0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EFP00008 {
            get {
                return ResourceManager.GetString("EFP00008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   lack of parent element data({0}).please check position of sheets of data file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EFP00009 {
            get {
                return ResourceManager.GetString("EFP00009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   value &apos;{0}&apos; declared in #var is already exists(row no. {1}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EFP00010 {
            get {
                return ResourceManager.GetString("EFP00010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   variable declaration &apos;{0}&apos; is invalid.(row no. {1}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EFP00011 {
            get {
                return ResourceManager.GetString("EFP00011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   condition &apos;{0}&apos; of #while is invalid.(row no. {1}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EFP00012 {
            get {
                return ResourceManager.GetString("EFP00012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   attribute of #link is invalid. this is valid before merge data, so you should confirm the bind variable if you use is. evaluated value is &quot;{0}&quot;.(row no. {1}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EFP00013 {
            get {
                return ResourceManager.GetString("EFP00013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   attribute of #picture is invalid. this is valid before merge data, so you should confirm the bind variable if you use is. evaluated value is &quot;{0}&quot;.(row no. {1}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EFP00014 {
            get {
                return ResourceManager.GetString("EFP00014", resourceCulture);
            }
        }
    }
}
